app/assets/stylesheets/custom.scss
app/views/static_pages/top.html.erb

viewのみです。
ログインフォームはまだ、アカウント作成機能等を作成していないので、sessionを利用できないのでコメントアウトしてあります

#4 topページview

---

app/assets/stylesheets/researches.scss
app/views/researches/item_research.html.erb

リサーチページのレイアウトのみ書きました。
コードレビューお願いします。

#1_modify_research_page_layout

---

Gemfile
Gemfile.lock
app/assets/stylesheets/custom.scss
app/assets/stylesheets/scaffolds.scss
app/controllers/users_controller.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/users/_form.html.erb
app/views/users/index.html.erb
app/views/users/new.html.erb
db/migrate/20190901050627_create_users.rb
db/schema.rb

アカウント作成機能を実装しました。
また、見た目等も少し修正他のですが、変な部分あったら教えてください

#9_Acount_create

---

Gemfile
Gemfile.lock
app/controllers/researches_controller.rb
app/views/researches/item_research.html.erb
config/environment.rb
db/schema.rb
db/seeds.rb

ページネーション 機能実装完了しました。
seeds.rbは仮でリサーチ商品をこちらで作成して、pushしましたが宜しかったでしょうか？
プルリクお願いします。

#8_add_paginate

---

app/assets/javascripts/sessions.coffee
app/assets/stylesheets/custom.scss
app/assets/stylesheets/sessions.scss
app/assets/stylesheets/static_pages.scss
app/controllers/application_controller.rb
app/controllers/sessions_controller.rb
app/controllers/users_controller.rb
app/helpers/sessions_helper.rb
app/models/user.rb
app/views/layouts/_header.html.erb
app/views/static_pages/top.html.erb
config/routes.rb
db/migrate/20190901050627_create_users.rb
db/migrate/20190925213715_add_remember_digest_to_users.rb
db/schema.rb
test/controllers/sessions_controller_test.rb

ログイン機能ならびにリメンバーミーも実装しましたので、確認お願いします。

ログイン機能の実装 #17

---

Gemfile
Gemfile.lock
app/assets/stylesheets/researches.scss
app/assets/stylesheets/scaffolds.scss
app/helpers/application_helper.rb
app/views/researches/item_research.html.erb
config/application.rb
config/locales/ja.yml
config/locales/models/models_ja.yml
db/schema.rb
db/seeds.rb

リサーチページテーブル内の日付・画像・URLリンク設定しました。
hover時のデザイン変更のため、scaffolds.scssいじっています。
他、gem 'i18n' 日本語化、config/locales/ja.yml, config/locales/models/models_ja.yml など新しいファイルあります。
またリサーチページ読み込みの為、seed変更しています。

#18_add-research-table-imgURL

---

Gemfile
Gemfile.lock
app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/views/users/_edit_form.html.erb
app/views/users/_form.html.erb
app/views/users/index.html.erb
db/migrate/20190901050627_create_users.rb
db/schema.rb
db/seeds.rb

gem fakerを追加しました。
そに伴って、seedsにサンプルユーザー作成のコードを追加しています。

ユーザー一覧の作成　#25

---

app/assets/stylesheets/custom.scss
app/controllers/items_controller.rb
app/controllers/stocks_controller.rb
app/models/item.rb
app/views/layouts/application.html.erb
app/views/stocks/inventory_control.html.erb
config/application.rb
config/routes.rb
db/seeds.rb

何度も申し訳けございません。custom.scssの大文字部分を小文字に修正しました。

#58 3.5在庫管理の実装インポート改訂3 

---

app/assets/stylesheets/custom.scss
app/controllers/items_controller.rb
app/controllers/stocks_controller.rb
app/models/item.rb
app/views/layouts/application.html.erb
app/views/stocks/inventory_control.html.erb
config/application.rb
config/routes.rb
db/seeds.rb

見栄え修正
下表を真ん中に
表二つの左面を合わせる
ボタン形式統一して位置合わす
インポートのフラッシュ機能修正
製品名のカラムができたので修正した
rails db:migrate:reset
rails db:seed
でデータ入れ替えお願いします

#52 3.5在庫管理の実装インポート改訂

---

app/assets/stylesheets/custom.scss
app/controllers/items_controller.rb
app/controllers/stocks_controller.rb
app/models/item.rb
app/views/layouts/application.html.erb
app/views/stocks/inventory_control.html.erb
config/application.rb
config/routes.rb
db/seeds.rb

#56 3.5在庫管理の実装インポート改訂2 

---

Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/custom.scss
app/controllers/items_controller.rb
app/views/stocks/inventory_control.html.erb
config/routes.rb

在庫商品一斉削除システム（ストック含む）
bundle install実行

#69.3.5在庫管理の商品一斉削除再

---

app/assets/javascripts/take_inventory.coffee
app/assets/stylesheets/stocks.scss
app/assets/stylesheets/take_inventory.scss
app/controllers/application_controller.rb
app/controllers/stocks_controller.rb
app/controllers/take_inventory_controller.rb
app/helpers/stocks_helper.rb
app/helpers/take_inventory_helper.rb
app/models/stock.rb
app/models/take_inventory.rb
app/views/layouts/_header.html.erb
app/views/stocks/product_inventory.html.erb
config/routes.rb
db/migrate/20190901053452_create_stocks.rb
db/migrate/20191015121720_create_take_inventories.rb
db/schema.rb
db/seeds.rb
test/controllers/take_inventory_controller_test.rb
test/fixtures/take_inventories.yml
test/models/take_inventory_test.rb

やっと商品棚卸しテーブル完成しました。
お待たせしました。
色々ロジック組んだので可読性が低いかもですがよろしくお願いします。

#49 商品棚卸しテーブル

---

app/assets/stylesheets/custom.scss
app/controllers/items_controller.rb
app/controllers/stocks_controller.rb
app/views/layouts/_header.html.erb
app/views/stocks/edit.html.erb
app/views/stocks/inventory_control.html.erb
config/routes.rb

商品データをクリックすれば在庫一覧表の表示
在庫一覧表の編集リンクをクリックすれば該当在庫データの編集可能に
商品一覧の２５個未満は赤字で表示（アラート）

#78 3.9 3.10在庫管理表のアコーディオン等

---

app/assets/stylesheets/custom.scss
app/assets/stylesheets/researches.scss
app/controllers/items_controller.rb
app/controllers/stocks_controller.rb
app/helpers/application_helper.rb
app/views/items/csv_scarceexport.csv.ruby
app/views/items/csv_soldoutexport.csv.ruby
app/views/items/edit.html.erb
app/views/items/product_scarce.html.erb
app/views/items/sold_out.html.erb
app/views/layouts/_header.html.erb
app/views/stocks/csv_export.csv.ruby
app/views/stocks/inventory_control.html.erb
config/routes.rb

84 8売切れ商品一覧表作成

---

app/assets/stylesheets/custom.scss
app/assets/stylesheets/stocks.scss
app/controllers/items_controller.rb
app/controllers/researches_controller.rb
app/models/item.rb
app/models/stock.rb
app/views/items/_form.html.erb
app/views/items/index.html.erb
app/views/items/new.html.erb
app/views/items/product_registration.html.erb
app/views/items/product_scarce.html.erb
app/views/items/sold_out.html.erb
app/views/layouts/_header.html.erb
app/views/stocks/inventory_control.html.erb
app/views/stocks/product_inventory.html.erb
config/routes.rb
db/seeds.rb

#89 商品登録機能実装

---

Gemfile.lock
app/assets/stylesheets/application.css
app/assets/stylesheets/header.css
app/helpers/application_helper.rb
app/views/items/edit.html.erb
app/views/layouts/_header.html.erb

アクティブ時リンクテキストの文字拡大。
製品番号更新時の見栄え修正。（出品リストの配置更新）。

#102ヘッダーアクティブ時リンク文字拡大

---

app/controllers/stocks_controller.rb

Reverts teamyosshi/china_item_inventory_manager#108

Revert "Revert "106 fix postgresql where like error""

---

app/assets/stylesheets/researches.scss
app/views/researches/item_research.html.erb

また再度cherry-pickしました。やり方が間違っているのかもしれないですが、git diff等しても自分の方ではconflict確認できませんでした。
とりあえず再pushしておきます。

リサーチページ想定レート再push #105

---

app/assets/stylesheets/custom.scss
app/assets/stylesheets/scaffolds.scss
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb
app/views/researches/item_research.html.erb

再度ヘッダー＆ログインページのコンフリクト解消プルリクです。

“conflict2_header_and_login_page”

---

app/controllers/researches_controller.rb
app/views/layouts/_header.html.erb
app/views/researches/item_research.html.erb

part_numberが不明なのとsimulate_priceの計算方法がいまいち分からないので一旦プルリクします。
計算方法等あればコメントください。

120 リサーチのチェックボタンを押したらItemが作成される様に

---

app/assets/stylesheets/custom.scss
app/assets/stylesheets/researches.scss
app/views/layouts/_header.html.erb
app/views/static_pages/top.html.erb
app/views/stocks/inventory_control.html.erb

“3_在庫管理ページのデザイン修正しました_#123”

---

app/assets/stylesheets/custom.scss
app/assets/stylesheets/researches.scss
app/views/researches/item_research.html.erb
app/views/stocks/buyitem.html.erb
app/views/stocks/inventory_control.html.erb

何度も失敗して申し訳ありません。
再々プルリクさせて頂きます。宜しくお願い致します。

#141_4_リサーチページのデザイン修正のコンフリクト解消

---

app/controllers/items_controller.rb
app/controllers/stocks_controller.rb
app/models/item.rb
app/models/stock.rb
app/views/items/edit.html.erb
app/views/stocks/edit.html.erb
app/views/stocks/stock_new.html.erb
config/locales/ja.yml

resolve #156 
- 1.バリデーションに引っ掛かると在庫編集に移行してそのまま入力してもエラーになる。
　→ただしく遷移されるよう修正
- 2.存在しない日付が選択できてしまう例2020/2/31
　→自動的に修正されるみたいなんで保留でいいかな。。
- 1.flashがwarningになっている　dangerのページがあるので他と統一した方がいいと思う。
　→統一！
- 2.何がバリデーションに引っかかったのか表示されるといいかと。
　→表示させてみました
- 3.前回の勉強会で突っ込まれていた、何が必須かどうかがわかるといいかも。
　→表示させてみました
- 4.本当に登録しますかの確認は必要か
　→これは欲しい。
- 1.更新するとCannot redirect to nil!になる
　→これは画面の遷移にsession使ってるからだと思う。開発時のみに起こる現象ではないかと
- 1.flashがwarningになっている　dangerのページがあるので他と統一した方がいいと思う。
　→統一！
- 2.何がバリデーションに引っかかったのか表示されるといいかと。
　→表示させてみました
- 3.前回の勉強会で突っ込まれていた、何が必須かどうかがわかるといいかも。
　→表示させてみました
　→については　１１と同じぺーじを表してましたのでバッサリカット。

12,13,14のもろもろの修正 #156

---

app/assets/stylesheets/custom.scss
app/assets/stylesheets/items.scss
app/assets/stylesheets/researches.scss
app/assets/stylesheets/scaffolds.scss
app/views/layouts/_header.html.erb
app/views/stocks/inventory_control.html.erb

【タスク説明】
・在庫管理ページ（アコーディオン内含む）のデザイン修正
・商品登録ページへボタンの修正（デザインと配置）
・管理者画面、一般ユーザー画面のデザイン統一
その他のページは当タスクでは（少ししか）触れていません。
ご確認お願いします。

#158 在庫管理ページのデザイン修正

---

app/assets/stylesheets/custom.scss
app/assets/stylesheets/researches.scss
app/assets/stylesheets/scaffolds.scss
app/assets/stylesheets/stocks.scss
app/assets/stylesheets/users.scss
app/views/items/edit.html.erb
app/views/items/product_scarce.html.erb
app/views/items/sold_out.html.erb
app/views/layouts/_header.html.erb
app/views/researches/item_research.html.erb
app/views/stocks/buyitem.html.erb
app/views/stocks/edit.html.erb
app/views/stocks/inventory_control.html.erb
app/views/stocks/product_inventory.html.erb
app/views/stocks/stock_new.html.erb
app/views/users/_edit_form.html.erb
app/views/users/index.html.erb
db/schema.rb

#161_全ページのレイアウト修正
